"""ip

Revision ID: 72357e242cd1
Revises: e397bc801914
Create Date: 2023-02-22 10:51:32.873285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72357e242cd1'
down_revision = 'e397bc801914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
